### ISSUE TITLE
Data path hardcoded

### ISSUE THREAD

**Issue by alecandido** [scarrazza/fiatlux#4]
Unfortunately, the data location is hard coded at "configure" time (the CMake equivalent, of course... might well be build time...):
https://github.com/scarrazza/fiatlux/blob/f25aebb4700d095733a0a6af2f5562ad8d85ff56/src/elastic.cc#L43
https://github.com/scarrazza/fiatlux/blob/f25aebb4700d095733a0a6af2f5562ad8d85ff56/CMakeLists.txt#L31

This is not a problem when compiling on the target system, but becomes a problem as soon as you try to compile on one system and run on another one.
In particular, it is a problem for the distribution of Python packages.

<details><summary>Error first obtained by @niclaurenti </summary>

```
RuntimeError: [ElasticPhoton::ElasticPhoton] data file not found in "/home/conda/feedstock_root/build_artifacts/fiatlux_1667476674586/work/_skbuild/linux-x86_64-3.9/cmake-install/src/fiatlux/share/fiatlux"
```

</details>

**Comment by scarrazza** [comment]
If this is really necessary, we could introduce a fiatlux-config/pkg-config file for fiatlux and use that instead of `DATA_PATH`.

**Comment by alecandido** [comment]
I would solve in a dirtier way: just embed data in the binary.

https://stackoverflow.com/q/410980
https://stackoverflow.com/q/4864866
https://manpages.ubuntu.com/manpages/jammy/en/man1/xxd.1.html

Once embedded, you do not need to care about files any longer.

**Comment by alecandido** [comment]
Thanks @scarrazza for the quick implementation!
